/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    WeButton: typeof import('./src/common/WeButton.vue')['default']
    WeCheckbox: typeof import('./src/form/WeCheckbox.vue')['default']
    WeColor: typeof import('./src/form/WeColor.vue')['default']
    WeDatepicker: typeof import('./src/form/WeDatepicker.vue')['default']
    WeField: typeof import('./src/form/WeField.vue')['default']
    WeFile: typeof import('./src/form/WeFile.vue')['default']
    WeModal: typeof import('./src/common/WeModal.vue')['default']
    WePassword: typeof import('./src/form/WePassword.vue')['default']
    WeRadio: typeof import('./src/form/WeRadio.vue')['default']
    WeSelect: typeof import('./src/form/WeSelect.vue')['default']
    WeTableBody: typeof import('./src/table/WeTableBody.vue')['default']
    WeText: typeof import('./src/form/WeText.vue')['default']
    WeTextarea: typeof import('./src/form/WeTextarea.vue')['default']
  }
}
