/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    WoButton: typeof import('./src/common/WoButton.vue')['default']
    WoCheckbox: typeof import('./src/form/WoCheckbox.vue')['default']
    WoColor: typeof import('./src/form/WoColor.vue')['default']
    WoDatepicker: typeof import('./src/form/WoDatepicker.vue')['default']
    WoField: typeof import('./src/form/WoField.vue')['default']
    WoFile: typeof import('./src/form/WoFile.vue')['default']
    WoLoadingIcon: typeof import('./src/common/WoLoadingIcon.vue')['default']
    WoModal: typeof import('./src/common/WoModal.vue')['default']
    WoPassword: typeof import('./src/form/WoPassword.vue')['default']
    WoRadio: typeof import('./src/form/WoRadio.vue')['default']
    WoSelect: typeof import('./src/form/WoSelect.vue')['default']
    WoTableBody: typeof import('./src/table/WoTableBody.vue')['default']
    WoTableFooter: typeof import('./src/table/WoTableFooter.vue')['default']
    WoText: typeof import('./src/form/WoText.vue')['default']
    WoTextarea: typeof import('./src/form/WoTextarea.vue')['default']
  }
}
