version: '3.7'

services:
  frontend:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/home/fancy-crud/fancy-crud
    ports:
      - '9090:9090'
    tty: true
    expose:
      - 9090

  server:
    build:
      context: ./server
    volumes:
      - ./server:/usr/share/backend
    ports:
      - '9000:9000'
    tty: true
