version: '3.7'

services:
  frontend:
    build: .
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/home/fancy-crud/fancy-crud
    ports:
      - '9091:9090'
    tty: true
