/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    WqButton: typeof import('./src/common/WqButton.vue')['default']
    WqCheckbox: typeof import('./src/form/WqCheckbox.vue')['default']
    WqColor: typeof import('./src/form/WqColor.vue')['default']
    WqDatepicker: typeof import('./src/form/WqDatepicker.vue')['default']
    WqField: typeof import('./src/form/WqField.vue')['default']
    WqFile: typeof import('./src/form/WqFile.vue')['default']
    WqModal: typeof import('./src/common/WqModal.vue')['default']
    WqPassword: typeof import('./src/form/WqPassword.vue')['default']
    WqRadio: typeof import('./src/form/WqRadio.vue')['default']
    WqSelect: typeof import('./src/form/WqSelect.vue')['default']
    WqTableBody: typeof import('./src/table/WqTableBody.vue')['default']
    WqText: typeof import('./src/form/WqText.vue')['default']
    WqTextarea: typeof import('./src/form/WqTextarea.vue')['default']
  }
}
