/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FButton: typeof import('./src/common/components/FButton.vue')['default']
    FCheckbox: typeof import('./src/forms/components/FCheckbox.vue')['default']
    FColor: typeof import('./src/forms/components/FColor.vue')['default']
    FDatepicker: typeof import('./src/forms/components/FDatepicker.vue')['default']
    FDeleteConfirmationModal: typeof import('./src/tables/components/FDeleteConfirmationModal.vue')['default']
    FFile: typeof import('./src/forms/components/FFile.vue')['default']
    FFileList: typeof import('./src/forms/components/FFileList.vue')['default']
    FFilter: typeof import('./src/filters/components/FFilter.vue')['default']
    FForm: typeof import('./src/forms/components/FForm.vue')['default']
    FFormBody: typeof import('./src/forms/components/FFormBody.vue')['default']
    FFormFooter: typeof import('./src/forms/components/FFormFooter.vue')['default']
    FFormHeader: typeof import('./src/forms/components/FFormHeader.vue')['default']
    FModal: typeof import('./src/common/components/FModal.vue')['default']
    FPassword: typeof import('./src/forms/components/FPassword.vue')['default']
    FRadio: typeof import('./src/forms/components/FRadio.vue')['default']
    FSelect: typeof import('./src/forms/components/FSelect.vue')['default']
    FTable: typeof import('./src/tables/components/FTable.vue')['default']
    FTableBody: typeof import('./src/tables/components/FTableBody.vue')['default']
    FTableHeaderActions: typeof import('./src/tables/components/FTableHeaderActions.vue')['default']
    FTableRowActions: typeof import('./src/tables/components/FTableRowActions.vue')['default']
    FTableRowFilePreview: typeof import('./src/tables/components/FTableRowFilePreview.vue')['default']
    FText: typeof import('./src/forms/components/FText.vue')['default']
    FTextarea: typeof import('./src/forms/components/FTextarea.vue')['default']
  }
}
