// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FButton: typeof import('./src/common/components/FButton.vue')['default']
    FDeleteConfirmationModal: typeof import('./src/tables/components/FDeleteConfirmationModal.vue')['default']
    FFilter: typeof import('./src/filters/components/FFilter.vue')['default']
    FForm: typeof import('./src/forms/components/FForm.vue')['default']
    FFormBody: typeof import('./src/forms/components/FFormBody.vue')['default']
    FFormFooter: typeof import('./src/forms/components/FFormFooter.vue')['default']
    FFormHeader: typeof import('./src/forms/components/FFormHeader.vue')['default']
    FModal: typeof import('./src/common/components/FModal.vue')['default']
    FTable: typeof import('./src/tables/components/FTable.vue')['default']
    FTableBody: typeof import('./src/tables/components/FTableBody.vue')['default']
    FTableHeaderActions: typeof import('./src/tables/components/FTableHeaderActions.vue')['default']
    FTableRowActions: typeof import('./src/tables/components/FTableRowActions.vue')['default']
    FTableRowFilePreview: typeof import('./src/tables/components/FTableRowFilePreview.vue')['default']
  }
}
