/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    FCheckboxViewer: typeof import('./src/viewer/FCheckboxViewer.vue')['default']
    FColorViewer: typeof import('./src/viewer/FColorViewer.vue')['default']
    FDateViewer: typeof import('./src/viewer/FDateViewer.vue')['default']
    FFileViewer: typeof import('./src/viewer/FFileViewer.vue')['default']
    FFormViewer: typeof import('./src/viewer/FFormViewer.vue')['default']
    FInputViewer: typeof import('./src/viewer/FInputViewer.vue')['default']
    FPasswordViewer: typeof import('./src/viewer/FPasswordViewer.vue')['default']
    FRadioViewer: typeof import('./src/viewer/FRadioViewer.vue')['default']
    FSelectViewer: typeof import('./src/viewer/FSelectViewer.vue')['default']
    FSidebar: typeof import('./src/viewer/FSidebar.vue')['default']
    FSidebarItem: typeof import('./src/viewer/FSidebarItem.vue')['default']
    FTableViewer: typeof import('./src/viewer/FTableViewer.vue')['default']
    FTextareaViewer: typeof import('./src/viewer/FTextareaViewer.vue')['default']
    TheMagic: typeof import('./src/plugins/TheMagic.vue')['default']
  }
}


