/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    WvButton: typeof import('./src/common/WvButton.vue')['default']
    WvCheckbox: typeof import('./src/fields/WvCheckbox.vue')['default']
    WvColor: typeof import('./src/fields/WvColor.vue')['default']
    WvDatepicker: typeof import('./src/fields/WvDatepicker.vue')['default']
    WvField: typeof import('./src/fields/WvField.vue')['default']
    WvFile: typeof import('./src/fields/WvFile.vue')['default']
    WvLoadingIcon: typeof import('./src/common/WvLoadingIcon.vue')['default']
    WvModal: typeof import('./src/common/WvModal.vue')['default']
    WvPassword: typeof import('./src/fields/WvPassword.vue')['default']
    WvRadio: typeof import('./src/fields/WvRadio.vue')['default']
    WvSelect: typeof import('./src/fields/WvSelect.vue')['default']
    WvTableBody: typeof import('./src/table/WvTableBody.vue')['default']
    WvText: typeof import('./src/fields/WvText.vue')['default']
    WvTextarea: typeof import('./src/fields/WvTextarea.vue')['default']
  }
}
