/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    WvButton: typeof import('./src/common/WvButton.vue')['default']
    WvCheckbox: typeof import('./src/form/WvCheckbox.vue')['default']
    WvColor: typeof import('./src/form/WvColor.vue')['default']
    WvDatepicker: typeof import('./src/form/WvDatepicker.vue')['default']
    WvField: typeof import('./src/form/WvField.vue')['default']
    WvFile: typeof import('./src/form/WvFile.vue')['default']
    WvModal: typeof import('./src/common/WvModal.vue')['default']
    WvPassword: typeof import('./src/form/WvPassword.vue')['default']
    WvRadio: typeof import('./src/form/WvRadio.vue')['default']
    WvSelect: typeof import('./src/form/WvSelect.vue')['default']
    WvTableBody: typeof import('./src/table/WvTableBody.vue')['default']
    WvTableFooter: typeof import('./src/table/WvTableFooter.vue')['default']
    WvText: typeof import('./src/form/WvText.vue')['default']
    WvTextarea: typeof import('./src/form/WvTextarea.vue')['default']
  }
}
