/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Autocomplete: typeof import('@oruga-ui/oruga-next/src/components/autocomplete/Autocomplete.vue')['default']
    Button: typeof import('@oruga-ui/oruga-next/src/components/button/Button.vue')['default']
    Carousel: typeof import('@oruga-ui/oruga-next/src/components/carousel/Carousel.vue')['default']
    CarouselItem: typeof import('@oruga-ui/oruga-next/src/components/carousel/CarouselItem.vue')['default']
    Checkbox: typeof import('@oruga-ui/oruga-next/src/components/checkbox/Checkbox.vue')['default']
    Collapse: typeof import('@oruga-ui/oruga-next/src/components/collapse/Collapse.vue')['default']
    Datepicker: typeof import('@oruga-ui/oruga-next/src/components/datepicker/Datepicker.vue')['default']
    DatepickerMonth: typeof import('@oruga-ui/oruga-next/src/components/datepicker/DatepickerMonth.vue')['default']
    DatepickerTable: typeof import('@oruga-ui/oruga-next/src/components/datepicker/DatepickerTable.vue')['default']
    DatepickerTableRow: typeof import('@oruga-ui/oruga-next/src/components/datepicker/DatepickerTableRow.vue')['default']
    Datetimepicker: typeof import('@oruga-ui/oruga-next/src/components/datetimepicker/Datetimepicker.vue')['default']
    Dropdown: typeof import('@oruga-ui/oruga-next/src/components/dropdown/Dropdown.vue')['default']
    DropdownItem: typeof import('@oruga-ui/oruga-next/src/components/dropdown/DropdownItem.vue')['default']
    Field: typeof import('@oruga-ui/oruga-next/src/components/field/Field.vue')['default']
    FieldBody: typeof import('@oruga-ui/oruga-next/src/components/field/FieldBody.vue')['default']
    Icon: typeof import('@oruga-ui/oruga-next/src/components/icon/Icon.vue')['default']
    Input: typeof import('@oruga-ui/oruga-next/src/components/input/Input.vue')['default']
    Inputitems: typeof import('@oruga-ui/oruga-next/src/components/inputitems/Inputitems.vue')['default']
    Loading: typeof import('@oruga-ui/oruga-next/src/components/loading/Loading.vue')['default']
    Menu: typeof import('@oruga-ui/oruga-next/src/components/menu/Menu.vue')['default']
    MenuItem: typeof import('@oruga-ui/oruga-next/src/components/menu/MenuItem.vue')['default']
    MenuList: typeof import('@oruga-ui/oruga-next/src/components/menu/MenuList.vue')['default']
    Modal: typeof import('@oruga-ui/oruga-next/src/components/modal/Modal.vue')['default']
    Notification: typeof import('@oruga-ui/oruga-next/src/components/notification/Notification.vue')['default']
    NotificationNotice: typeof import('@oruga-ui/oruga-next/src/components/notification/NotificationNotice.vue')['default']
    Pagination: typeof import('@oruga-ui/oruga-next/src/components/pagination/Pagination.vue')['default']
    PaginationButton: typeof import('@oruga-ui/oruga-next/src/components/pagination/PaginationButton.vue')['default']
    Radio: typeof import('@oruga-ui/oruga-next/src/components/radio/Radio.vue')['default']
    Select: typeof import('@oruga-ui/oruga-next/src/components/select/Select.vue')['default']
    Sidebar: typeof import('@oruga-ui/oruga-next/src/components/sidebar/Sidebar.vue')['default']
    SimpleAutocomplete: typeof import('@oruga-ui/oruga-next/src/components/autocomplete/tests/SimpleAutocomplete.vue')['default']
    SimpleCollapse: typeof import('@oruga-ui/oruga-next/src/components/collapse/tests/SimpleCollapse.vue')['default']
    Skeleton: typeof import('@oruga-ui/oruga-next/src/components/skeleton/Skeleton.vue')['default']
    Slider: typeof import('@oruga-ui/oruga-next/src/components/slider/Slider.vue')['default']
    SliderThumb: typeof import('@oruga-ui/oruga-next/src/components/slider/SliderThumb.vue')['default']
    SliderTick: typeof import('@oruga-ui/oruga-next/src/components/slider/SliderTick.vue')['default']
    StepItem: typeof import('@oruga-ui/oruga-next/src/components/steps/StepItem.vue')['default']
    Steps: typeof import('@oruga-ui/oruga-next/src/components/steps/Steps.vue')['default']
    Switch: typeof import('@oruga-ui/oruga-next/src/components/switch/Switch.vue')['default']
    TabItem: typeof import('@oruga-ui/oruga-next/src/components/tabs/TabItem.vue')['default']
    Table: typeof import('@oruga-ui/oruga-next/src/components/table/Table.vue')['default']
    TableColumn: typeof import('@oruga-ui/oruga-next/src/components/table/TableColumn.vue')['default']
    TableMobileSort: typeof import('@oruga-ui/oruga-next/src/components/table/TableMobileSort.vue')['default']
    TablePagination: typeof import('@oruga-ui/oruga-next/src/components/table/TablePagination.vue')['default']
    Tabs: typeof import('@oruga-ui/oruga-next/src/components/tabs/Tabs.vue')['default']
    Timepicker: typeof import('@oruga-ui/oruga-next/src/components/timepicker/Timepicker.vue')['default']
    Tooltip: typeof import('@oruga-ui/oruga-next/src/components/tooltip/Tooltip.vue')['default']
    Upload: typeof import('@oruga-ui/oruga-next/src/components/upload/Upload.vue')['default']
  }
}
