/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FwButton: typeof import('./src/common/FwButton.vue')['default']
    FwCheckbox: typeof import('./src/form/FwCheckbox.vue')['default']
    FwColor: typeof import('./src/form/FwColor.vue')['default']
    FwDatepicker: typeof import('./src/form/FwDatepicker.vue')['default']
    FwField: typeof import('./src/form/FwField.vue')['default']
    FwFile: typeof import('./src/form/FwFile.vue')['default']
    FwPassword: typeof import('./src/form/FwPassword.vue')['default']
    FwRadio: typeof import('./src/form/FwRadio.vue')['default']
    FwSelect: typeof import('./src/form/FwSelect.vue')['default']
    FwTableBody: typeof import('./src/table/FwTableBody.vue')['default']
    FwTableFooter: typeof import('./src/table/FwTableFooter.vue')['default']
    FwText: typeof import('./src/form/FwText.vue')['default']
    FwTextarea: typeof import('./src/form/FwTextarea.vue')['default']
    FwToast: typeof import('./src/common/FwToast.vue')['default']
  }
}
