// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FButton: typeof import('./components/FButton.vue')['default']
    FCheckbox: typeof import('./components/form/FCheckbox.vue')['default']
    FCheckboxMultiple: typeof import('./components/form/FCheckboxMultiple.vue')['default']
    FCheckboxSingle: typeof import('./components/form/FCheckboxSingle.vue')['default']
    FColor: typeof import('./components/form/FColor.vue')['default']
    FControlContainer: typeof import('./components/FControlContainer.vue')['default']
    FControlHintMessage: typeof import('./components/FControlHintMessage.vue')['default']
    FControlLabel: typeof import('./components/FControlLabel.vue')['default']
    FControlWrap: typeof import('./components/FControlWrap.vue')['default']
    FForm: typeof import('./components/form/FForm.vue')['default']
    FFormFooter: typeof import('./components/form/FFormFooter.vue')['default']
    FFormHeader: typeof import('./components/form/FFormHeader.vue')['default']
    FFormMain: typeof import('./components/form/FFormMain.vue')['default']
    FInput: typeof import('./components/form/FInput.vue')['default']
    FInputDate: typeof import('./components/form/FInputDate.vue')['default']
    FInputFile: typeof import('./components/form/FInputFile.vue')['default']
    FInputFilePreview: typeof import('./components/form/FInputFilePreview.vue')['default']
    FInputPassword: typeof import('./components/form/FInputPassword.vue')['default']
    FModal: typeof import('./components/FModal.vue')['default']
    FModalCard: typeof import('./components/FModalCard.vue')['default']
    FNotification: typeof import('./components/FNotification.vue')['default']
    FPagination: typeof import('./components/FPagination.vue')['default']
    FRadio: typeof import('./components/form/FRadio.vue')['default']
    FSelect: typeof import('./components/form/FSelect.vue')['default']
    FTable: typeof import('./components/FTable.vue')['default']
    FTableBody: typeof import('./components/FTableBody.vue')['default']
    FTableFooter: typeof import('./components/FTableFooter.vue')['default']
    FTableHeader: typeof import('./components/FTableHeader.vue')['default']
    FTableRow: typeof import('./components/FTableRow.vue')['default']
    FTextarea: typeof import('./components/form/FTextarea.vue')['default']
  }
}

export { }
