name: Node.js CI

on:
  push:
    branches: [main, alpha, beta, next]

jobs:
  # quality:

  #   runs-on: ${{ matrix.os }}

  #   strategy:
  #     matrix:
  #       # node-version: [10.x, 12.x, 14.x, 15.x, 16.x, 17.x]
  #       node-version: [16.x]
  #       # os: [ubuntu-latest, windows-latest]
  #       os: [ubuntu-latest]
  #       # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 8
  #         run_install: |
  #           - recursive: true
  #             args: [--frozen-lockfile, --strict-peer-dependencies]
  #           - args: [--global, gulp, prettier, typescript]
  #     # - run: yarn test

  publish:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: install dependencies
        run: pnpm install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: fake-semantic
        with:
          semantic_version: 19
          dry_run: true
          working_directory: ./packages/core
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
      - name: Do something when a new release published
        if: steps.fake-semantic.outputs.new_release_published == 'true'
        run: |
          pnpm -w run release ${{ steps.fake-semantic.outputs.new_release_version }}
          pnpm --filter "./packages/**" publish

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic   # Need an `id` for output variables
        with:
          semantic_version: 19
          dry_run: true
          working_directory: ./packages/core
          branches: |
            [
              '+([0-9])?(.{+([0-9]),x}).x',
              'main',
              'next',
              'next-major',
              {
                name: 'beta',
                prerelease: true
              },
              {
                name: 'alpha',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
