name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  quality:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x, 16.x, 17.x]
        node-version: [16.x]
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      # - run: npm test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build
      - name: Semantic Release
        run: |
          yarn add -D semantic-release@^19.0.5    \
          "@semantic-release/changelog"              \
          "@semantic-release/commit-analyzer"        \
          "@semantic-release/github"                 \
          "@semantic-release/release-notes-generator"
          npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
