name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  quality:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: ./dist

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-results
          path: ./dist
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - name: Semantic Release
        run: |
          npm i semantic-release@^19.0.5    \
          "@semantic-release/changelog"              \
          "@semantic-release/commit-analyzer"        \
          "@semantic-release/github"                 \
          "@semantic-release/release-notes-generator"
          npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
